### ISSUE TITLE
Update Software Engineering Ideas that influence me

### ISSUE THREAD

**Issue by bbkane** [bbkane/www.bbkane.com#5]

**Comment by bbkane** [comment]
Add https://grugbrain.dev/ too

**Comment by bbkane** [comment]
And https://youtu.be/9Q1RMueVHAg

**Comment by bbkane** [comment]
https://simonwillison.net/2022/Jan/12/how-i-build-a-feature/

**Comment by bbkane** [comment]
https://m.youtube.com/watch?v=tzr7hRXcwkw

**Comment by bkane-msft** [comment]
https://www.youtube.com/watch?v=8aGhZQkoFbQ
